### ISSUE TITLE
Generate test assemblies using CADQuery

### ISSUE THREAD

**Issue by sree314** [sree314/stepcvt#13]
We'll need test STEP models for running our tests. Although we can use existing STEP models, we'll create a few simple models to keep our tests running fast and to avoid downloads.

Create a `models.py` file in the `tests` directory with a function per model. Each function should return a CADQuery assembly. You can use the tutorial models in CADQuery to start with.

**Comment by ymh1003** [comment]
I've created a pull request with 3 models. I will add more but I'm not sure how simple these test models should be. Is the level of these 3 models fine or should I make it lower/higher?

**Comment by sree314** [comment]
Done.
