### ISSUE TITLE
Implement the choices framework

### ISSUE THREAD

**Issue by sree314** [sree314/stepcvt#33]
I've implemented the data model choices as classes in `stepcvt/choices/__init__.py` in the `choices-ui` branch. The choices framework intends to represent user choices that affect which parts will eventually be printed.

Samantha's notes from class can be found here:

https://github.com/sree314/csc293-fall23/blob/main/tech-planning/DataModelForChoices.md

There are no tests, but please write tests before writing code, so we're clear about the specification. Feel free to email me and/or comment on this issue to figure out what the intention of each of those classes is.

The rough pseudocode portion of the notes can be ignored for now, that code represents how to apply a user's choices to the generation of STL files.

You can work in the `choices-ui` branch.

**Comment by redrn** [comment]
merged implementation into roy-a7 on commit #65986ea
