### ISSUE TITLE
subparser for choices module

### ISSUE THREAD

**Issue by redrn** [sree314/stepcvt#40]
Implement CLI subparser for choices module, 
functionalities include but not limited to:
 - define choices
 - edit choices
 - remove choices
 - apply choices to parts

**Comment by redrn** [comment]
Specific CLI subcommand interface:

# Add a new chooser:
`stepcvt choices add-chooser [--choices-type TYPE] TEXT VARNAME --values (TEXT:VARNAME[:COND])+`
 - Specify chooser type, options are `{single, multi, boolean}` default is a SingleChooser
 - Specify `text` and `varname` of the Chooser
 - Specify a list of ChoiceValue, in the format of `TEXT:VARNAME[:COND]`
   - `text:varname:condition` are fields of ChoiceValue separated by `:`, `condition` is optional
  
# Replace a component of a chooser:
`stepcvt choices edit VARNAME [--choice-value TEXT] (TEXT:VARNAME[:COND])+`
 - Specify `varname` of the Chooser to edit
 - Optionally, specify `value` of the ChoiceValue in the specified Chooser to replace
   - If `--choice-value` is not set, replace the entire ChoiceValue array in the specified Chooser
 - Provide list of replacement ChoiceValue, in the format `TEXT:VARNAME[:COND]`

# Remove a chooser or a component of it
`stepcvt choices remove VARNAME [--choice-value TEXT] [--cond]`
 - Specify `varname` of the chooser to remove
 - Optionally, specify `text` of a ChoiceValue to remove the ChoiceValue instead of the chooser
 - Optionally, specify `--cond` to indicate removing the condition of the ChoiceValue.

# Apply user choices 
`stepcvt choices apply (VARNAME=VALUE(,EXTRA_VALUES)*)+`
 - User choices are specified in the format of `varname=value(,extra_values)*`
   - `varname` specifies the name of the chooser
   - `value(,extra_values)` is the value the user provided for the given chooser. This could be a comma separated list.

**Comment by redrn** [comment]
TODO: add support for ChoiceEffect classes

**Comment by sree314** [comment]
Roy, could you add examples for each of the command line options above. That may help clarify _what_ the command is supposed to do, and how to use it.

**Comment by redrn** [comment]
> Roy, could you add examples for each of the command line options above. That may help clarify _what_ the command is supposed to do, and how to use it.

Updated the documentation to include examples, pulled from comments in the code.

**Comment by redrn** [comment]
TODO: change apply subcommand to prompt the user for selecting choices and then either 1) export all based on user chocices 2) apply choices calculation and strip all choices information for the new json config

**Comment by redrn** [comment]
All intended functionalities are completed and tested. We can work on simplifying the interface later. Closing as of now
