### ISSUE TITLE
Add more tests for to_dict() in project class & Fix the bug

### ISSUE THREAD

**Issue by ymh1003** [sree314/stepcvt#45]
The `to_dict()` in `project` class does not have a corresponding test in `test_project.py` that checks for individual partinfo - sree
Fix the functionality of `to_dict()` and `from_dict()` in `project` class - Samantha

**Comment by sree314** [comment]
Project to_dict does not recurse into cad source, etc. so it does not return that information.

**Comment by sree314** [comment]
@skriegsman , I added the test, please write code to make to_dict() recursive. Please work in this branch

**Comment by skriegsman** [comment]
I made sure my branch (swkriegsman_a6_addSource) is up to date. I added sources to the to_dict() function but I didnt make it recursive. Either way the pytests doesnt throw an error about it so I am not sure what exactly I am meant to fix

**Comment by ymh1003** [comment]
@skriegsman , the newly added test is on branch `45-add-more-tests-for-to_dict-in-project-class-fix-the-bug`. Please work in that branch.
