### ISSUE TITLE
Load and write to json file in scripts

### ISSUE THREAD

**Issue by AdiraBlumenthal** [sree314/stepcvt#61]
# load from JSON function

# write to JSON function 

    # if args.command == "make"
    #   something else
    # else 
        # p = load_from_json(args.jsonFile)
        # sys.exit(args.func(args))

**Comment by redrn** [comment]
Centralized Loading and unloading of Project json file should appear only in the toplevel `stepcvt` script. Subcommand scripts shouldn't have to deal with loading json themselves. The created Project object would be passed to subcommand function call on dispatch. We should modify our subcommand function to take a Project argument followed by args. The dispatch would look like `args.func(project, args)`.

We should all change our subcommands functions to reflect this change.

**Comment by skriegsman** [comment]
proj.py methods updated by commit 4a8d95fc882abe782b65ff4ca5c02cdde9d67bfa on CLI branch
