### ISSUE TITLE
Level 2 Deserialization

### ISSUE THREAD

**Issue by redrn** [sree314/stepcvt#63]
Level 2 deserialization loads the json config without loading the STEP files. This would be done by having `load` function for every classes.

**Comment by sree314** [comment]
I added preliminary tests for this functionality in the `test_load.py` file.

The idea is that top-level project `load()` function will pass the path down to `load()` function of a cadsource object.

@skriegsman, you should implement the project load() function.

@Asai-Yume, you should implement the cadsource load() function

**Comment by sree314** [comment]
This is all on the cli branch.

@redrn, can you serve as reviewer for the code and merge it into cli?

**Comment by skriegsman** [comment]
Added load() method to proj class in commit da35c113905f4d05defaf2ef54bb028f425dc312
