### ISSUE TITLE
fix issue with cadsource assemblies

### ISSUE THREAD

**Issue by AdiraBlumenthal** [sree314/stepcvt#69]
<img width="987" alt="Screenshot 2023-12-01 at 10 44 34 AM" src="https://github.com/sree314/stepcvt/assets/40038122/d0ec705a-39d9-4f64-b209-28d5628ab4ef">

**Comment by Asai-Yume** [comment]
I made some changes, let me know if the issue persists

**Comment by ymh1003** [comment]
I think I've fixed the issue in my commit `c2bd033`. At least now the commands related to the `part` class work. For testing, I assume that the stepfile resides in the `tests` directory.

**Comment by skriegsman** [comment]
> @skriegsman Hi Sam, I need to know how to access a source in a project given args.step_path, please take a look at the code in source.py and the stepcvt script.

If you have project p then you can access CADsource objects in p.sources like....

for cs in p.sources:
    cs = something
