### ISSUE TITLE
Implement STLConversionInfo

### ISSUE THREAD

**Issue by sree314** [sree314/stepcvt#8]
This involves implement the `to_dict` and `from_dict`, as well as patching up the init method.

**Comment by AdiraBlumenthal** [comment]
I feel like a lot of these errors from the tests are import issues from files/areas I didn't touch. I've done all the config set up that we were supposed to so I'm confused about these. 
<img width="932" alt="Screenshot 2023-10-21 at 2 59 28 PM" src="https://github.com/sree314/stepcvt/assets/40038122/717536ab-8646-4f27-9f8e-82491ca33f76">

**Comment by sree314** [comment]
Yes, seems to be after adding stepreader.
@ymh1003 You probably need to add more files.

**Comment by ymh1003** [comment]
I fixed this issue in my latest pull request.
